"""Emit the Google Apps Script that builds the Sample A rating forms.

Reads the frozen per-rater sheets data/sample_a_sheet_<rater>.csv and writes
data/sample_a_forms.gs, which creates one Google Form per rater showing name, description and
category for each concept as a required 1-5 multiple-choice question titled with the rater's
item number. The sheets are the source of truth; nothing is resampled.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from paths import PANEL  # noqa: E402

PANEL_DATA = PANEL / "data"
SHEET_FILE = str(PANEL_DATA / "sample_a_sheet_{rater}.csv")
SCRIPT_FILE = PANEL_DATA / "sample_a_forms.gs"

RATERS = ("roach", "ramsey", "koslicki", "hodges")
MAX_DESCRIPTION = 1_200

RUBRIC = """\
You are rating 100 biomedical knowledge-graph concepts on how generic vs. \
specific each one is as a standalone answer to a biomedical query (for \
example: "what treats X?", "what is associated with Y?").

Rate each concept from 1 to 5:
1 - Generic: too general to be a useful standalone answer.
5 - Specific: a concrete, useful answer.
Use the values in between for intermediate degrees.

Judge genericness only - not human relevance, clinical importance, or \
familiarity. Non-human concepts (insect anatomy, plant genes, veterinary \
diseases) are rated by the same standard as human ones.

Rate from the name, description and category shown - please do not look \
concepts up in external resources."""

CHOICES = ("1", "2", "3", "4", "5")

TEMPLATE = """\
// Sample A rating forms. Generated by sample_a_forms_build.py
// - do not edit by hand; regenerate instead.
//
// At script.google.com: New project, paste this file over Code.gs, run
// buildAll, authorize when prompted, then read the form URLs from the
// execution log. If the run times out partway, run the remaining
// build_<rater> functions individually.

const RUBRIC = {rubric};
const CHOICES = {choices};
const ITEMS = {items};

function buildForm(rater) {{
  const form = FormApp.create('Generic concept rating - ' + rater);
  form.setDescription(RUBRIC);
  ITEMS[rater].forEach(function (item) {{
    const title = item.n + '. ' + item.name;
    let help = 'Category: ' + item.category;
    if (item.description) {{
      help += '\\n\\nDescription: ' + item.description;
    }}
    form.addMultipleChoiceItem()
      .setTitle(title)
      .setHelpText(help)
      .setChoiceValues(CHOICES)
      .setRequired(true);
  }});
  Logger.log(rater + ' form to fill out: ' + form.getPublishedUrl());
  Logger.log(rater + ' form to edit:     ' + form.getEditUrl());
}}

{builders}

function buildAll() {{
{calls}
}}
"""


def load(rater: str) -> list[dict]:
    """Read one rater's frozen sheet into form items, in the rater's order.

    Descriptions longer than MAX_DESCRIPTION characters are cut at a word break with "[...]".
    """
    sheet = pd.read_csv(SHEET_FILE.format(rater=rater))

    items = []
    for row in sheet.itertuples():
        description = row.description if isinstance(row.description, str) else ""
        if len(description) > MAX_DESCRIPTION:
            description = description[:MAX_DESCRIPTION].rsplit(" ", 1)[0] + " [...]"
        items.append(
            {
                "n": row.item,
                "name": row.name,
                "category": row.category,
                "description": description,
            }
        )
    return items


def main() -> None:
    """Render the Apps Script from every rater's sheet and write it."""
    items = {rater: load(rater) for rater in RATERS}

    builders = "\n\n".join(
        f"function build_{rater}() {{ buildForm('{rater}'); }}" for rater in RATERS
    )
    calls = "\n".join(f"  build_{rater}();" for rater in RATERS)

    script = TEMPLATE.format(
        rubric=json.dumps(RUBRIC),
        choices=json.dumps(list(CHOICES)),
        items=json.dumps(items, indent=1),
        builders=builders,
        calls=calls,
    )

    with open(SCRIPT_FILE, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(script)
    total = sum(len(rows) for rows in items.values())
    print(
        f"wrote {SCRIPT_FILE}: {total} items across "
        f"{len(RATERS)} forms, {SCRIPT_FILE.stat().st_size:,} bytes"
    )


if __name__ == "__main__":
    main()
